### ISSUE TITLE
Your Cart

### ISSUE THREAD

**Issue by muragewanjohi** [kevgichohi/cleanup#10]
Show all bought items

**Comment by z-01** [comment]
The listview was not expanding with the addition of new items because there were too many items (views) on the screen, the final solution was to implement a custom listview that expands with the number of items added.
![2016-08-30 08 07 09](https://cloud.githubusercontent.com/assets/21059569/18081260/015e96ac-6ea2-11e6-9f1b-814f77547261.png)

**Comment by kevgichohi** [comment]
Ok looks good.
Please send the revised APK
